#!/bin/bash

echo "Cloudflare SSL/TLS Configuration Steps for Cloud Run"
echo "=================================================="
echo ""
echo "1. Log into Cloudflare Dashboard: https://dash.cloudflare.com"
echo "2. Select domain: swacktech.com"
echo ""
echo "3. SSL/TLS Settings:"
echo "   - Go to SSL/TLS > Overview"
echo "   - Change SSL/TLS encryption mode to 'Flexible'"
echo "   This is required because Cloud Run handles SSL termination"
echo ""
echo "4. Edge Certificates:"
echo "   - Go to SSL/TLS > Edge Certificates"
echo "   - Enable 'Always Use HTTPS'"
echo "   - Set Minimum TLS Version to 1.2"
echo "   - Enable 'Automatic HTTPS Rewrites'"
echo ""
echo "5. DNS Settings:"
echo "   - Go to DNS"
echo "   - Ensure all A and AAAA records are using DNS only (grey cloud)"
echo "   - Records should point to Google Cloud Run IPs:"
echo "     A Records:"
echo "     - 216.239.32.21"
echo "     - 216.239.34.21"
echo "     - 216.239.36.21"
echo "     - 216.239.38.21"
echo ""
echo "     AAAA Records:"
echo "     - 2001:4860:4802:32::15"
echo "     - 2001:4860:4802:34::15"
echo "     - 2001:4860:4802:36::15"
echo "     - 2001:4860:4802:38::15"
echo ""
echo "6. After configuring:"
echo "   - Wait 5-10 minutes for changes to propagate"
echo "   - Clear DNS cache:"
echo "     sudo dscacheutil -flushcache"
echo "     sudo killall -HUP mDNSResponder"
echo ""
echo "7. Test the connection:"
echo "   curl -v https://swacktech.com"