version: '3.8'

services:
  vault-query:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount config file
      - ./config.yaml:/app/config.yaml:ro
      # Mount cache directory for persistence
      - ./cache:/app/cache
    env_file:
      - .env
    # Default command (can be overridden)
    command: ["0xF9e31984F6c90621c362aE50EC60BFc467633f08", "-v"]
    # Restart policy
    restart: unless-stopped
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # Healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.path.exists('/app/cache')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"