# RPC Configuration
rpc_endpoints:
  - https://eth.llamarpc.com
  - https://rpc.ankr.com/eth
  - https://eth-mainnet.public.blastapi.io
  - https://ethereum.publicnode.com
  - https://1rpc.io/eth
  - https://rpc.mevblocker.io
  - https://cloudflare-eth.com

# Contract Addresses
contracts:
  factory: "0xeA6876DDE9e3467564acBeE1Ed5bac88783205E0"

# Batch Processing
batch_sizes:
  controller_discovery: 3  # Number of controllers to query in parallel
  loan_info: 5  # Number of loans to query in parallel

# Error Handling
error_limits:
  max_consecutive_errors: 10  # Stop after this many consecutive errors
  rate_limit_retries: 3  # Number of times to retry on rate limit

# Cache Configuration
cache:
  token_info_ttl: 43200  # 12 hours in seconds
  loan_info_ttl: 14400   # 4 hours in seconds
  web3_call_ttl: 300     # 5 minutes in seconds

# Output Configuration
output:
  save_context: true  # Whether to save analysis context
  color_output: true  # Whether to use colored output