rpc_endpoints:
  default:
    - "http://192.168.40.201:8545"  # Local Ethereum node
  gcp:
    - "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"  # Alchemy
    - "https://mainnet.infura.io/v3/${INFURA_PROJECT_ID}"       # Infura
    - "https://rpc.ankr.com/eth/${ANKR_API_KEY}"                # Ankr

batch_sizes:
  vault_discovery: 10
  loan_processing: 50

error_limits:
  max_consecutive_errors: 5
  max_retries: 3
  retry_delay: 1.0

cache:
  enabled: true
  storage: "sqlite"
  location: ".cache/web3_cache.db"
  ttl: 14400  # 4 hours in seconds
  cleanup_interval: 3600  # Run cleanup every hour

output:
  save_context: true

contracts:
  factory: "0xeA6876DDE9e3467564acBeE1Ed5bac88783205E0"
  factory_abi: |
    [
      {
        "stateMutability": "view",
        "type": "function",
        "name": "controllers",
        "inputs": [
          {
            "name": "n",
            "type": "uint256"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "address"
          }
        ]
      },
      {
        "stateMutability": "view",
        "type": "function",
        "name": "market_count",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "uint256"
          }
        ]
      }
    ]