apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: swacktech-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/https-only: "true"
    run.googleapis.com/ingress-allow-http: "false"
    run.googleapis.com/allow-unauthenticated: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: gcr.io/homelab-424523/swacktech-frontend:latest
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: BASE_URL
              value: "https://swacktech.com"
          startupProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true